image: maven:3.5.2-jdk-8
stages:
- test
- build
services:
- 'mysql:5.5'
- 'mongo:latest'
dependencies:
    - build
variables:
 MYSQL_DATABASE: userDb
 MYSQL_CI_URL: jdbc:mysql://mysql/userDb
 MYSQL_USER: app_root
 MYSQL_PASSWORD: root
 MYSQL_ROOT_PASSWORD: root

 MONGO_HOST: mongo
 MONGO_PORT: "27017"
 MONGO_DB: UserDB
 MONGO_URL: "mongodb://$MONGO_HOST:$MONGO_PORT/$MONGO_DB"
maven-test:
 stage: test
 script: 'mvn test'

maven-build:
 stage: build
 script: 'mvn package'
